<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="@yield('description','Skills for Life. Enterprise for Livelihoods. Opportunities for Youth.')"><title>@yield('title','Lwotowone Enterprises Ltd')</title><link rel="stylesheet" href="{{ asset('assets/app.css') }}"></head><body>
<a class="skip" href="#main">Skip to content</a><header><a class="brand" href="/"> <span class="brand-mark">L</span><span>LWOTOWONE<small>ENTERPRISES LTD</small></span></a><nav aria-label="Main navigation"><a href="/pages/about">About us</a><a href="/explore/programs">Programmes</a><a href="/explore/courses">Learn</a><a href="/explore/opportunities">Opportunities</a><a href="/explore/events">Events</a><a href="/explore/posts">Stories</a><a href="/contact">Contact</a>@auth<a class="button small" href="/dashboard">Dashboard</a>@else<a href="/login">Sign in</a><a class="button small" href="/register">Join us</a>@endauth</nav></header>
<div class="shell">@auth<aside><strong>{{ auth()->user()->name }}</strong><small>{{ ucwords(auth()->user()->role) }}</small><a href="/dashboard">Overview</a>@if(auth()->user()->staff())@foreach(config('modules') as $key=>$meta)@if(\App\Services\Catalog::allowed(auth()->user(),$key))<a href="/admin/{{ $key }}">{{ $meta['title'] }}</a>@endif
@endforeach
@if(auth()->user()->manager() || auth()->user()->role==='instructor')<a href="/admin/reviews/submissions">Assess practical work</a>@endif
@if(auth()->user()->manager() || auth()->user()->role==='mentor')<a href="/admin/reviews/bookings">Mentorship requests</a>@endif
@if(auth()->user()->manager())@foreach(['practice_logs'=>'Verify skills','applications'=>'Applications','event_registrations'=>'Attendance','contacts'=>'Enquiries','audit_logs'=>'Audit trail'] as $key=>$label)<a href="/admin/reviews/{{ $key }}">{{ $label }}</a>@endforeach<a href="/admin/reports/impact.csv">Export impact report</a>@endif
@else @foreach(['learn'=>'My learning','practice'=>'Practical skills','mentorship'=>'Mentorship','opportunities'=>'Opportunities','enterprise'=>'Enterprise & earnings','events'=>'Events','notifications'=>'Notifications','profile'=>'My profile'] as $key=>$label)<a href="/portal/{{ $key }}">{{ $label }}</a>@endforeach @endif
<form method="post" action="/logout">@csrf<button class="secondary">Sign out</button></form></aside>@endauth
<main id="main">@if(session('success'))<div class="notice success" role="status">{{ session('success') }}</div>@endif @if($errors->any())<div class="notice error" role="alert"><ul>@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif @yield('content')</main></div>
<footer><div><strong>Lwotowone Enterprises Ltd</strong><p>Skills for Life. Enterprise for Livelihoods. Opportunities for Youth.</p></div><div><nav aria-label="Organisation pages">@foreach($contentPages as $navPage)<a href="/pages/{{ $navPage->slug }}">{{ $navPage->title }}</a>@endforeach</nav><a href="/pages/privacy">Privacy</a> · <a href="/pages/terms">Terms</a><p>© {{ date('Y') }} Lwotowone Enterprises Ltd · Uganda</p></div></footer><script src="{{ asset('assets/app.js') }}" defer></script></body></html>
