@extends('layout')
@section('title','Enrollment management')
@section('content')
<div class="page-wrap">
@php
    $secretPattern = '/password|remember|token|secret|api_key|fcm|credentials/i';
    $looksEncrypted = fn ($value) => is_string($value) && (str_starts_with($value, 'enc:') || (str_starts_with($value, 'eyJ') && str_contains((string) base64_decode($value, true), '"mac"')));
    $attributesOf = fn ($row) => is_object($row) && method_exists($row, 'getAttributes') ? $row->getAttributes() : (array) $row;
    $moreDetails = fn (array $attributes, array $skip = []) => collect($attributes)
        ->reject(fn ($value, $key) => in_array($key, $skip, true) || preg_match($secretPattern, (string) $key) === 1 || $looksEncrypted($value))
        ->map(fn ($value, $key) => ['label' => \Illuminate\Support\Str::headline((string) $key), 'value' => $value, 'group' => 'More details'])
        ->values()->all();
@endphp
<span class="eyebrow">Learning and content</span>
<h1 class="page-title">Enrollment</h1>
<p class="page-intro">Set up cohorts and settlements. Activate course access once payment is confirmed.</p>
<x-filter-bar
    :action="'/admin/enrollment'"
    :search="$filters['q']"
    searchLabel="Search learners"
    searchPlaceholder="Search learners"
    :statusOptions="['all'=>'All statuses','pending'=>'Pending payment','enrolled'=>'Enrolled','incomplete'=>'Incomplete profile']"
    :status="$filters['status']"
    statusLabel="Enrollment status"
    idPrefix="enrollment"
/>
<div class="tabs" data-tabs><div class="tab-list" role="tablist" aria-label="Enrollment management sections"><button type="button" role="tab" id="enrollment-tab-cohorts" aria-controls="enrollment-panel-cohorts" aria-selected="true">Cohorts</button><button type="button" role="tab" id="enrollment-tab-settlements" aria-controls="enrollment-panel-settlements" aria-selected="false" tabindex="-1">Settlements</button><button type="button" role="tab" id="enrollment-tab-payments" aria-controls="enrollment-panel-payments" aria-selected="false" tabindex="-1">Payment confirmation</button><button type="button" role="tab" id="enrollment-tab-outcomes" aria-controls="enrollment-panel-outcomes" aria-selected="false" tabindex="-1">Learner outcomes</button></div>
<section class="tab-panel" role="tabpanel" id="enrollment-panel-cohorts" aria-labelledby="enrollment-tab-cohorts">
<section class="panel enrollment-panel"><div class="mel-panel-heading"><div><h2>Enrollment cohorts</h2><p>Use <code>{prefix}</code>, <code>{cohort}</code>, <code>{year}</code> and <code>{sequence}</code> in number formats.</p></div><span class="tag">{{ $cohorts->count() }} cohorts</span></div>
    <form method="post" action="/admin/enrollment/cohorts" class="grid">@csrf
        <div class="field"><label for="cohort-name">Cohort name</label><input id="cohort-name" name="name" required></div>
        <div class="field"><label for="cohort-category">Enrollment category</label><input id="cohort-category" name="enrollment_category" required></div>
        <div class="field"><label for="cohort-prefix">Learner number prefix</label><input id="cohort-prefix" name="learner_number_prefix" required></div>
        <div class="field"><label for="cohort-format">Number format</label><input id="cohort-format" name="learner_number_format" value="{prefix}-{year}-{sequence}" required></div>
        <div class="field"><label for="cohort-sequence">Next sequence</label><input id="cohort-sequence" type="number" name="next_sequence" value="1" min="1" required></div>
        <div class="field"><label for="cohort-padding">Sequence digits</label><input id="cohort-padding" type="number" name="sequence_padding" value="4" min="1" max="10" required></div>
        <div class="field"><label><input type="checkbox" name="active" value="1" checked> Active for enrollment</label></div><div class="field"><button type="submit">Add cohort</button></div>
    </form>
    <div class="table-wrap"><table><thead><tr><th>Cohort</th><th>Category</th><th>Prefix</th><th>Number format</th><th>Next sequence</th><th>Status</th><th>Actions</th></tr></thead><tbody>
        @forelse($cohorts as $cohort)<tr><td>{{ $cohort->name }}<small>ID {{ $cohort->id }}</small></td><td>{{ $cohort->enrollment_category }}</td><td>{{ $cohort->learner_number_prefix }}</td><td>{{ $cohort->learner_number_format }}</td><td>{{ $cohort->next_sequence }}</td><td>{{ $cohort->active?'Active':'Inactive' }}</td><td><div class="actions"><x-record-view-trigger :dialogId="'view-cohort-'.$cohort->id" :name="$cohort->name" /><button class="secondary small icon-action" type="button" data-dialog-open="edit-cohort-{{ $cohort->id }}" title="Edit cohort" aria-label="Edit cohort"><i class="fas fa-pen" aria-hidden="true"></i></button><form method="post" action="/admin/enrollment/cohorts/{{ $cohort->id }}" data-confirm="Remove this cohort?">@csrf @method('DELETE')<button class="danger small icon-action" title="Delete cohort" aria-label="Delete cohort"><i class="fas fa-trash-alt" aria-hidden="true"></i></button></form></div>
            <dialog class="form-dialog" id="edit-cohort-{{ $cohort->id }}"><div class="dialog-heading"><h2>Edit {{ $cohort->name }}</h2><button class="secondary small" type="button" data-dialog-close>Close</button></div><form class="dialog-form" method="post" action="/admin/enrollment/cohorts/{{ $cohort->id }}">@csrf @method('PUT')@foreach(['name'=>'Cohort name','enrollment_category'=>'Enrollment category','learner_number_prefix'=>'Learner number prefix','learner_number_format'=>'Number format','next_sequence'=>'Next sequence','sequence_padding'=>'Sequence digits'] as $field=>$label)<div class="field"><label for="cohort-{{ $cohort->id }}-{{ $field }}">{{ $label }}</label><input id="cohort-{{ $cohort->id }}-{{ $field }}" name="{{ $field }}" value="{{ $cohort->$field }}" @if(in_array($field,['next_sequence','sequence_padding']))type="number" min="1"@endif required></div>@endforeach<div class="field"><label><input type="checkbox" name="active" value="1" @checked($cohort->active)> Active</label></div><div class="dialog-actions"><button>Save cohort</button></div></form></dialog>
            <x-record-view-dialog :id="'view-cohort-'.$cohort->id" :title="$cohort->name" :fields="array_merge([['label'=>'Cohort name','value'=>$cohort->name],['label'=>'Enrollment category','value'=>$cohort->enrollment_category],['label'=>'Learner number prefix','value'=>$cohort->learner_number_prefix],['label'=>'Number format','value'=>$cohort->learner_number_format],['label'=>'Next sequence','value'=>$cohort->next_sequence],['label'=>'Sequence digits','value'=>$cohort->sequence_padding],['label'=>'Status','value'=>$cohort->active?'Active':'Inactive']], $moreDetails($attributesOf($cohort), ['name','enrollment_category','learner_number_prefix','learner_number_format','next_sequence','sequence_padding','active']))" />
        </td></tr>@empty<tr><td colspan="7">No cohorts yet. Add one above.</td></tr>@endforelse
    </tbody></table></div>
</section>
</section>
<section class="tab-panel" role="tabpanel" id="enrollment-panel-settlements" aria-labelledby="enrollment-tab-settlements" hidden>
<section class="panel enrollment-panel"><div class="mel-panel-heading"><div><h2>Refugee settlements</h2><p>Shown to learners who identify as refugees.</p></div><span class="tag">{{ $settlements->count() }} settlements</span></div>
    <form method="post" action="/admin/enrollment/settlements" class="toolbar">@csrf<div class="field"><label for="settlement-name">Settlement name</label><input id="settlement-name" name="name" required></div><button>Add settlement</button></form>
    <div class="actions">@forelse($settlements as $settlement)<span class="tag">{{ $settlement->name }}<form method="post" action="/admin/enrollment/settlements/{{ $settlement->id }}" data-confirm="Remove this settlement?">@csrf @method('DELETE')<button class="danger small" aria-label="Remove {{ $settlement->name }}">Remove</button></form></span>@empty<p>No settlements yet.</p>@endforelse</div>
</section>
</section>
<section class="tab-panel" role="tabpanel" id="enrollment-panel-payments" aria-labelledby="enrollment-tab-payments" hidden>
<section class="panel enrollment-panel"><div class="mel-panel-heading"><div><h2>Payment confirmation</h2><p>Confirm verified payment to assign a cohort and activate course access.</p></div><span class="tag">{{ $pendingLearners->count() }} learners</span></div>
    @if($trialLearners->isNotEmpty())<h3>Trial course payment confirmations</h3><div class="table-wrap"><table><thead><tr><th>Learner</th><th>Course</th><th>Trial expires</th><th>Confirm verified payment</th></tr></thead><tbody>@foreach($trialLearners as $trial)<tr><td>{{ $trial->name }}<small>{{ $trial->email }}</small></td><td>{{ $trial->title }}</td><td>{{ $trial->trial_expires_at }}</td><td><x-record-view-trigger :dialogId="'view-trial-'.$trial->user_id.'-'.$trial->course_id" :name="$trial->name" /><form method="post" action="/admin/enrollment/learners/{{ $trial->user_id }}/confirm-payment">@csrf<input type="hidden" name="course_id" value="{{ $trial->course_id }}"><select name="cohort_id" required aria-label="Cohort for {{ $trial->name }}"><option value="">Select cohort</option>@foreach($cohorts->where('active',true) as $cohort)<option value="{{ $cohort->id }}">{{ $cohort->name }}</option>@endforeach</select><button type="submit">Confirm course payment</button></form><x-record-view-dialog :id="'view-trial-'.$trial->user_id.'-'.$trial->course_id" :title="$trial->name" :fields="array_merge([['label'=>'Learner','value'=>$trial->name],['label'=>'Email','value'=>$trial->email],['label'=>'Course','value'=>$trial->title],['label'=>'Trial expires','value'=>$trial->trial_expires_at]], $moreDetails($attributesOf($trial), ['name','email','title','trial_expires_at']))" /></td></tr>@endforeach</tbody></table></div>@endif
    <section class="panel"><h3>Bulk enrollment CSV</h3><p>Enroll learners by email. Profiles must be complete and a course selected. Importing confirms payment and activates access, so verify payments first.</p><a class="button secondary small" href="/admin/enrollment/template.csv">Download CSV template</a><p><code>email,cohort_id</code>. Use an active cohort ID from the Cohorts tab, or leave blank to use the default cohort below. Up to 1,000 learners per file. One invalid row stops the whole import. Already enrolled learners are skipped.</p><form method="post" action="/admin/enrollment/import" enctype="multipart/form-data" class="grid">@csrf<div class="field"><label for="enrollment-csv">CSV file</label><input id="enrollment-csv" type="file" name="csv" accept=".csv,text/csv" required></div><div class="field"><label for="import-cohort">Default cohort (optional)</label><select id="import-cohort" name="cohort_id"><option value="">Use cohort IDs from CSV</option>@foreach($cohorts->where('active',true) as $cohort)<option value="{{ $cohort->id }}">{{ $cohort->name }} (ID {{ $cohort->id }})</option>@endforeach</select></div><div class="field"><button type="submit">Upload and enroll learners</button></div></form></section>
    <form id="bulk-enrollment" method="post" action="/admin/enrollment/bulk" class="actions">@csrf<label for="bulk-cohort">Cohort for selected learners</label><select id="bulk-cohort" name="cohort_id" required><option value="">Select cohort</option>@foreach($cohorts->where('active',true) as $cohort)<option value="{{ $cohort->id }}">{{ $cohort->name }}</option>@endforeach</select><button type="submit">Enroll selected learners</button><button type="button" class="secondary" data-select-enrollment>Select all eligible learners</button></form>
    <div class="table-wrap"><table><thead><tr><th>Learner</th><th>Email</th><th>Selected course</th><th>Created</th><th>Assign cohort</th></tr></thead><tbody>
        @forelse($pendingLearners as $learner)@php $courseTitle=DB::table('courses')->where('id',$learner->selected_course_id)->value('title'); @endphp<tr><td><label><input type="checkbox" name="learner_ids[]" value="{{ $learner->id }}" form="bulk-enrollment" @disabled(!$learner->profile_complete)> {{ $learner->name }}</label>@unless($learner->profile_complete)<small>Incomplete profile</small>@endunless</td><td>{{ $learner->email }}</td><td>{{ $courseTitle }}</td><td>{{ \Illuminate\Support\Carbon::parse($learner->created_at)->format('d M Y') }}</td><td><x-record-view-trigger :dialogId="'view-learner-'.$learner->id" :name="$learner->name" /><form method="post" action="/admin/enrollment/learners/{{ $learner->id }}/confirm-payment" class="actions">@csrf<label class="sr-only" for="payment-cohort-{{ $learner->id }}">Cohort for {{ $learner->name }}</label><select id="payment-cohort-{{ $learner->id }}" name="cohort_id" required><option value="">Select cohort</option>@foreach($cohorts->where('active',true) as $cohort)<option value="{{ $cohort->id }}">{{ $cohort->name }}</option>@endforeach</select><button class="small icon-action" title="Confirm payment and enrollment" aria-label="Confirm payment for {{ $learner->name }}"><i class="fas fa-check" aria-hidden="true"></i></button></form><x-record-view-dialog :id="'view-learner-'.$learner->id" :title="$learner->name" :fields="array_merge([['label'=>'Name','value'=>$learner->name],['label'=>'Email','value'=>$learner->email],['label'=>'Profile complete','value'=>(bool) $learner->profile_complete],['label'=>'Selected course','value'=>$courseTitle],['label'=>'Registered','value'=>\Illuminate\Support\Carbon::parse($learner->created_at)->format('d M Y')]], $moreDetails($attributesOf($learner), ['name','email','profile_complete','created_at']))" /></td></tr>@empty<tr><td colspan="5">No learners are waiting for payment confirmation.</td></tr>@endforelse
    </tbody></table></div>
</section>
</section>
<section class="tab-panel" role="tabpanel" id="enrollment-panel-outcomes" aria-labelledby="enrollment-tab-outcomes" hidden>
    <section class="panel enrollment-panel"><div class="mel-panel-heading"><div><h2>Learner outcomes</h2><p>Record verified outcomes and next steps after training.</p></div><span class="tag">{{ $outcomeLearners->count() }} learner records</span></div>
        <div class="table-wrap"><table><thead><tr><th>Learner</th><th>Learner number</th><th>After-work status</th><th>Verified outcomes</th><th>Actions</th></tr></thead><tbody>
        @forelse($outcomeLearners as $learner)<tr><td>{{ $learner->name }}</td><td>{{ $learner->learner_no??'Pending' }}</td><td>{{ $learner->after_work_status??'—' }}</td><td>{{ \Illuminate\Support\Str::limit($learner->verified_outcomes??$learner->other_verified_outcome,90) }}</td><td><x-record-view-trigger :dialogId="'view-outcome-'.$learner->id" :name="$learner->name" /><x-record-view-dialog :id="'view-outcome-'.$learner->id" :title="$learner->name" :fields="array_merge([['label'=>'Learner','value'=>$learner->name],['label'=>'Learner number','value'=>$learner->learner_no??'Pending'],['label'=>'After-work status','value'=>$learner->after_work_status??null],['label'=>'After-work pathway','value'=>$learner->after_work_pathway??null],['label'=>'Verified outcomes','value'=>$learner->verified_outcomes??null],['label'=>'Other verified outcome','value'=>$learner->other_verified_outcome??null]], $moreDetails($attributesOf($learner), ['name','learner_no','after_work_status','after_work_pathway','verified_outcomes','other_verified_outcome']))" /><button type="button" class="secondary small icon-action" data-dialog-open="learner-outcomes-{{ $learner->id }}" title="Update learner outcomes" aria-label="Update outcomes for {{ $learner->name }}"><i class="fas fa-pen" aria-hidden="true"></i></button><dialog class="form-dialog" id="learner-outcomes-{{ $learner->id }}"><div class="dialog-heading"><h2>Update {{ $learner->name }} outcomes</h2><button class="secondary small" type="button" data-dialog-close>Close</button></div><form class="dialog-form" method="post" action="/admin/enrollment/learners/{{ $learner->id }}/outcomes">@csrf @method('PUT')<div class="field"><label for="verified-{{ $learner->id }}">Verified learner outcomes</label><textarea id="verified-{{ $learner->id }}" name="verified_outcomes">{{ $learner->verified_outcomes }}</textarea></div><div class="field"><label for="other-outcome-{{ $learner->id }}">Other verified outcome</label><textarea id="other-outcome-{{ $learner->id }}" name="other_verified_outcome">{{ $learner->other_verified_outcome }}</textarea></div><div class="field"><label for="work-status-{{ $learner->id }}">After-work status</label><select id="work-status-{{ $learner->id }}" name="after_work_status"><option value="">Select status</option>@foreach(['Working','Self-employed','Studying','Seeking work','Other'] as $status)<option value="{{ $status }}" @selected($learner->after_work_status===$status)>{{ $status }}</option>@endforeach</select></div><div class="field"><label for="pathway-{{ $learner->id }}">After-work pathway</label><input id="pathway-{{ $learner->id }}" name="after_work_pathway" value="{{ $learner->after_work_pathway }}"></div><div class="dialog-actions"><button>Save outcome updates</button></div></form></dialog></td></tr>@empty<tr><td colspan="5">No learner profiles are available.</td></tr>@endforelse
        </tbody></table></div>
    </section>
</section>
</div>
</div>
@endsection
