@extends('layout')
@section('content')
<div class="page-wrap">
    <span class="eyebrow">Event registration and attendance</span><h1 class="page-title">Events</h1>
    <p class="page-intro">Create an event, publish it, and share its registration link or QR code. Track participant registrations and record attendance from each event's roster.</p>
    <form class="filter-form" method="get" action="/admin/events"><div class="field search-field"><label for="event-search">Search events</label><input id="event-search" name="q" value="{{ $filters['q'] }}"></div><div class="field"><label for="event-status">Status</label><select id="event-status" name="status">@foreach(['all'=>'All statuses','draft'=>'Draft','published'=>'Published','cancelled'=>'Cancelled'] as $key=>$label)<option value="{{ $key }}" @selected($filters['status']===$key)>{{ $label }}</option>@endforeach</select></div><div class="filter-actions"><button type="submit">Apply</button><a href="/admin/events">Reset</a></div></form>
    <div class="toolbar"><button type="button" data-dialog-open="create-event"><i class="fas fa-plus" aria-hidden="true"></i> Add event</button></div>
    <div class="panel table-wrap cms-table-wrap"><table class="cms-table"><caption class="sr-only">Events and participation totals</caption><thead><tr><th class="column-primary" scope="col">Event</th><th class="column-date" scope="col">When / where</th><th class="column-number" scope="col">Registered</th><th class="column-number" scope="col">Attended</th><th class="column-status" scope="col">Status</th><th class="column-actions" scope="col">Actions</th></tr></thead><tbody>
    @forelse($events as $event)<tr><td class="column-primary"><strong>{{ $event->title }}</strong><small>{{ \Illuminate\Support\Str::limit($event->description,90) }}</small></td><td class="column-date">{{ \Carbon\Carbon::parse($event->starts_at)->format('d M Y, H:i') }}<small>{{ $event->location }}</small></td><td class="column-number">{{ $event->registered_count }}{{ $event->capacity?' / '.$event->capacity:'' }}</td><td class="column-number">{{ $event->attended_count }}</td><td class="column-status"><span class="status-badge" data-status="{{ $event->status }}">{{ ucfirst($event->status) }}</span></td><td class="column-actions"><div class="actions"><button class="secondary small icon-action" type="button" data-dialog-open="share-event-{{ $event->id }}" title="Registration link and QR" aria-label="Share {{ $event->title }}"><i class="fas fa-qrcode" aria-hidden="true"></i></button><a class="button secondary small icon-action" href="/admin/events/{{ $event->id }}/attendance" title="Attendance roster" aria-label="Attendance for {{ $event->title }}"><i class="fas fa-user-check" aria-hidden="true"></i></a><button type="button" class="secondary small icon-action" data-dialog-open="edit-event-{{ $event->id }}" title="Edit event" aria-label="Edit {{ $event->title }}"><i class="fas fa-pen" aria-hidden="true"></i></button></div></td></tr>@empty<tr><td colspan="6" class="table-empty">No events match. Add your first event to generate a registration link and QR.</td></tr>@endforelse
    </tbody></table>@include('partials.pagination',['rows'=>$events])</div>
    <dialog class="form-dialog" id="create-event" aria-labelledby="create-event-title"><div class="dialog-heading"><h2 id="create-event-title">Add event</h2><button type="button" class="secondary small" data-dialog-close>Close</button></div><form class="dialog-form" method="post" action="/admin/events">@csrf<input type="hidden" name="_modal_id" value="create-event">@php $record=null; @endphp@include('admin.fields',['formId'=>'create-event'])<p class="muted">A registration link and QR code are generated automatically. Participants can register when the event is published, before its start time.</p><div class="dialog-actions"><button type="submit">Save event</button></div></form></dialog>
    @foreach($events as $event)
        <x-share-dialog :id="'share-event-'.$event->id" :title="$event->title" :url="url('/events/'.$event->registration_token)" :qrUrl="'/admin/events/'.$event->id.'/qr.svg'" />
        <dialog class="form-dialog" id="edit-event-{{ $event->id }}" aria-labelledby="edit-event-title-{{ $event->id }}"><div class="dialog-heading"><h2 id="edit-event-title-{{ $event->id }}">Edit event</h2><button type="button" class="secondary small" data-dialog-close>Close</button></div><form class="dialog-form" method="post" action="/admin/events/{{ $event->id }}">@csrf @method('PUT')<input type="hidden" name="_modal_id" value="edit-event-{{ $event->id }}">@php $record=$event; @endphp@include('admin.fields',['formId'=>'edit-event-'.$event->id])<div class="dialog-actions"><button type="submit">Save changes</button></div></form></dialog>
    @endforeach
    @if($errors->any()&&old('_modal_id'))<div data-reopen-dialog="{{ old('_modal_id') }}" hidden></div>@endif
</div>
@endsection
