@extends('layout')
@section('content')
<div class="page-wrap"><a href="/admin/events">Back to events</a><span class="eyebrow">Registration and attendance</span><h1 class="page-title">{{ $event->title }}</h1><p class="page-intro">{{ \Carbon\Carbon::parse($event->starts_at)->format('d M Y, H:i') }} · {{ $event->location }}. Attendance can be recorded once this published event starts.</p>
<div class="stats"><div class="stat"><strong>{{ $counts->except('cancelled')->sum() }}</strong><span>Active registrations</span></div><div class="stat"><strong>{{ $counts->get('attended',0) }}</strong><span>Attended</span></div><div class="stat"><strong>{{ $counts->get('absent',0) }}</strong><span>Absent</span></div><div class="stat"><strong>{{ $counts->get('cancelled',0) }}</strong><span>Cancelled</span></div></div>
<form class="filter-form" method="get"><div class="field search-field"><label for="roster-search">Participant name or email</label><input id="roster-search" name="q" value="{{ $filters['q'] }}"></div><div class="field"><label for="roster-status">Status</label><select id="roster-status" name="status">@foreach(['all','registered','attended','absent','cancelled'] as $status)<option value="{{ $status }}" @selected($filters['status']===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="filter-actions"><button type="submit">Apply</button><a href="/admin/events/{{ $event->id }}/attendance">Reset</a></div></form>
<div class="toolbar"><a class="button secondary" href="/admin/events/{{ $event->id }}/attendance.csv">Export attendance CSV</a></div>
<div class="panel table-wrap cms-table-wrap"><table class="cms-table"><caption class="sr-only">Event attendance roster</caption><thead><tr><th class="column-primary">Participant</th><th class="column-context">Contact</th><th class="column-status">Status</th><th class="column-date">Attendance recorded</th><th class="column-actions">Actions</th></tr></thead><tbody>
@forelse($registrations as $registration)<tr><td class="column-primary"><strong>{{ $registration->name }}</strong><small>{{ $registration->user_id?'Participant account':'Guest registration' }} · {{ \Carbon\Carbon::parse($registration->created_at)->format('d M Y') }}</small></td><td class="column-context">{{ $registration->email }}<small>{{ $registration->phone }}</small></td><td class="column-status"><span class="status-badge" data-status="{{ $registration->status }}">{{ ucfirst($registration->status) }}</span></td><td class="column-date">{{ $registration->attendance_recorded_at?\Carbon\Carbon::parse($registration->attendance_recorded_at)->format('d M Y, H:i'):'Not recorded' }}</td><td class="column-actions">
<form class="actions" method="post" action="/admin/events/{{ $event->id }}/attendance/{{ $registration->id }}">@csrf<label class="sr-only" for="attendance-{{ $registration->id }}">Status for {{ $registration->name }}</label><select id="attendance-{{ $registration->id }}" name="status">@foreach(['registered'=>'Registered','attended'=>'Present','absent'=>'Absent','cancelled'=>'Cancelled'] as $status=>$label)<option value="{{ $status }}" @selected($registration->status===$status) @disabled(in_array($status,['attended','absent'])&&(now()->lt($event->starts_at)||$event->status!=='published'||$registration->status==='cancelled'))>{{ $label }}</option>@endforeach</select><button class="small" type="submit">Save</button></form>
</td></tr>@empty<tr><td colspan="5" class="table-empty">No participants match these filters.</td></tr>@endforelse</tbody></table>@include('partials.pagination',['rows'=>$registrations])</div></div>
@endsection
