@extends('layout')
@section('title','MEL reports | Lwotowone')
@section('content')
<span class="eyebrow">Monitoring, evaluation and learning</span><h1>MEL reports</h1>
<div class="stats">@foreach($counts as $label=>$value)<div class="stat"><strong>{{ $value }}</strong><span>{{ $label }}</span></div>@endforeach</div>
<section class="panel"><h2>Learner access and profiles</h2><div class="table-wrap"><table><thead><tr><th>Learner No</th><th>Name</th><th>Phone</th><th>Email</th><th>Enrollment category</th><th>Gender</th><th>Location</th><th>Urban/Rural</th><th>Age</th><th>Refugee</th><th>Settlement</th><th>PWD</th><th>Impairment</th><th>Education</th><th>Learner status</th><th>Verified outcomes</th><th>Other outcome</th><th>YIW before</th><th>Objective</th><th>After-work status</th><th>Pathway</th><th>Created</th><th>Updated</th><th>Payment</th></tr></thead><tbody>@forelse(\App\Models\User::where('role','participant')->latest()->get() as $learner)<tr><td>{{ $learner->learner_no }}</td><td>{{ $learner->name }}</td><td>{{ $learner->phone }}</td><td>{{ $learner->email }}</td><td>{{ $learner->enrollment_category }}</td><td>{{ $learner->gender }}</td><td>{{ $learner->location }}</td><td>{{ $learner->urban_rural }}</td><td>{{ $learner->learner_age }}</td><td>{{ $learner->refugee?'Yes':'No' }}</td><td>{{ $learner->settlement }}</td><td>{{ $learner->pwd?'Yes':'No' }}</td><td>{{ $learner->impairment }}</td><td>{{ $learner->education_level }}</td><td>{{ $learner->learner_status }}</td><td>{{ $learner->verified_outcomes }}</td><td>{{ $learner->other_verified_outcome }}</td><td>{{ $learner->yiw_before }}</td><td>{{ $learner->transformation_objective }}</td><td>{{ $learner->after_work_status }}</td><td>{{ $learner->after_work_pathway }}</td><td>{{ $learner->created_at }}</td><td>{{ $learner->updated_at }}</td><td>@if($learner->learning_access_paid)Paid / active @else Pending <form method="post" action="/admin/mel/learners/{{ $learner->id }}/confirm-payment">@csrf<button class="small">Confirm payment</button></form>@endif</td></tr>@empty<tr><td colspan="24">No learner accounts yet.</td></tr>@endforelse</tbody></table></div></section>
@foreach($categories as $key=>$meta)
<section class="panel"><h2>{{ $meta[0] }}</h2><form method="post" action="/admin/mel/{{ $key }}" class="grid">@csrf
@foreach(array_slice($meta,1) as [$field,$label,$type])<div class="field"><label>{{ $label }}</label><input name="{{ $field }}" type="{{ $type }}" @if($type==='number')step="any" min="0"@endif></div>@endforeach
<div class="field"><button type="submit">Add {{ $meta[0] }} record</button></div></form>
<div class="table-wrap"><table><thead><tr>@foreach(array_slice($meta,1) as [$field,$label])<th>{{ $label }}</th>@endforeach<th>Created at</th><th>Actions</th></tr></thead><tbody>
@forelse($records->where('category',$key) as $record)@php $values=(array)json_decode($record->data,true); @endphp<tr>@foreach(array_slice($meta,1) as [$field])<td>{{ $values[$field]??'' }}</td>@endforeach<td>{{ $record->created_at }}</td><td><form method="post" action="/admin/mel/{{ $key }}/{{ $record->id }}" data-confirm="Delete this record?">@csrf @method('DELETE')<button class="danger small">Delete</button></form></td></tr>@empty<tr><td colspan="{{ count($meta)+1 }}">No records yet.</td></tr>@endforelse</tbody></table></div></section>
@endforeach
<section class="panel"><h2>Payment gateways and methods</h2><p>Configure the payment destinations shown to learners. Add IOTEC, bank accounts, mobile money, or merchant codes.</p>
<form method="post" action="/admin/mel/payment-gateways" class="grid">@csrf
<div class="field"><label>Display name</label><input name="name" placeholder="e.g. Programme tuition" required></div>
<div class="field"><label>Payment type</label><select name="provider_type" required>@foreach(['IOTEC','Bank','Mobile Money','Merchant Code','Other'] as $type)<option>{{ $type }}</option>@endforeach</select></div>
<div class="field"><label>Provider / bank</label><input name="provider" placeholder="IOTEC, bank name, telecom"></div>
<div class="field"><label>Account holder</label><input name="account_name"></div>
<div class="field"><label>Account / phone number</label><input name="account_number"></div>
<div class="field"><label>Merchant code</label><input name="merchant_code"></div>
<div class="field"><label>Currency</label><select name="currency" required>@foreach(['UGX','USD','EUR','GBP','KES'] as $currency)<option>{{ $currency }}</option>@endforeach</select></div>
<div class="field"><label>Amount (optional)</label><input type="number" min="0" step="0.01" name="amount"></div>
<div class="field"><label>Payment instructions</label><textarea name="instructions" placeholder="Reference to use, steps, or other learner instructions"></textarea></div>
<div class="field"><label><input type="checkbox" name="active" value="1" checked> Show to learners</label></div><div class="field"><button type="submit">Add payment option</button></div></form>
<div class="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Provider</th><th>Account holder</th><th>Account / phone</th><th>Merchant code</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($gateways as $gateway)<tr><td>{{ $gateway->name }}</td><td>{{ $gateway->provider_type }}</td><td>{{ $gateway->provider }}</td><td>{{ $gateway->account_name }}</td><td>{{ $gateway->account_number }}</td><td>{{ $gateway->merchant_code }}</td><td>{{ $gateway->amount?number_format($gateway->amount,2).' '.$gateway->currency:'—' }}</td><td>{{ $gateway->active?'Active':'Hidden' }}</td><td><form method="post" action="/admin/mel/payment-gateways/{{ $gateway->id }}" data-confirm="Delete this payment option?">@csrf @method('DELETE')<button class="danger small">Delete</button></form></td></tr>@empty<tr><td colspan="9">No payment methods configured.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><h2>Supporting documents</h2><form method="post" action="/admin/mel/documents" enctype="multipart/form-data" class="grid">@csrf<div class="field"><label>Category</label><input name="category" required></div><div class="field"><label>Document</label><input name="document" required></div><div class="field"><label>Description</label><input name="description"></div><div class="field"><label>File</label><input name="file" type="file" required></div><button>Upload document</button></form>
<div class="table-wrap"><table><thead><tr><th>Category</th><th>Document</th><th>Description</th><th>File</th><th>Size</th><th>Uploaded by</th><th>Uploaded at</th><th>Actions</th></tr></thead><tbody>@forelse($documents as $doc)<tr><td>{{ $doc->category }}</td><td>{{ $doc->document }}</td><td>{{ $doc->description }}</td><td>{{ basename($doc->file_path) }}</td><td>{{ number_format($doc->size/1024,1) }} KB</td><td>{{ \App\Models\User::find($doc->uploaded_by)?->name }}</td><td>{{ $doc->created_at }}</td><td><div class="actions"><a class="button small" href="/admin/mel/documents/{{ $doc->id }}/download">Download</a><form method="post" action="/admin/mel/documents/{{ $doc->id }}">@csrf @method('DELETE')<button class="danger small">Delete</button></form></div></td></tr>@empty<tr><td colspan="8">No supporting documents uploaded.</td></tr>@endforelse</tbody></table></div></section>
@endsection
