@extends('layout')
@section('title','MEL reports | Lwotowone')
@section('content')
<span class="eyebrow">Monitoring, evaluation and learning</span><h1>MEL reports</h1>
<div class="stats">@foreach($counts as $label=>$value)<div class="stat"><strong>{{ $value }}</strong><span>{{ $label }}</span></div>@endforeach</div>
<section class="panel"><h2>Learner access and profiles</h2><div class="table-wrap"><table>
<thead><tr><th>Learner No</th><th>Name</th><th>Phone</th><th>Email</th><th>Course</th><th>Cohort</th><th>Enrollment category/date</th><th>Gender</th><th>Location</th><th>Urban/Rural</th><th>Age</th><th>Refugee</th><th>Settlement</th><th>PWD</th><th>Impairment</th><th>Education</th><th>Status</th><th>Employed</th><th>Employer</th><th>Verified outcomes</th><th>Other outcome</th><th>Objective</th><th>After-work status</th><th>Pathway</th><th>Created</th><th>Updated</th><th>Actions</th></tr></thead><tbody>
@forelse(\App\Models\User::where('role','participant')->latest()->get() as $learner)
<tr><td>{{ $learner->learner_no??'Pending payment' }}</td><td>{{ $learner->name }}</td><td>{{ $learner->phone }}</td><td>{{ $learner->email }}</td><td>{{ DB::table('courses')->where('id',$learner->selected_course_id)->value('title') }}</td><td>{{ DB::table('mel_cohorts')->where('id',$learner->cohort_id)->value('name') }}</td><td>{{ $learner->enrollment_category }} {{ $learner->enrollment_date?'· '.$learner->enrollment_date:'' }}</td><td>{{ $learner->gender }}</td><td>{{ $learner->location }}</td><td>{{ $learner->urban_rural }}</td><td>{{ $learner->learner_age }}</td><td>{{ $learner->refugee?'Yes':'No' }}</td><td>{{ $learner->settlement }}</td><td>{{ $learner->pwd?'Yes':'No' }}</td><td>{{ $learner->impairment }}</td><td>{{ $learner->education_level }}</td><td>{{ $learner->learner_status }}</td><td>{{ $learner->employed?'Yes':'No' }}</td><td>{{ $learner->employer_name }}</td><td>{{ $learner->verified_outcomes }}</td><td>{{ $learner->other_verified_outcome }}</td><td>{{ $learner->transformation_objective }}</td><td>{{ $learner->after_work_status }}</td><td>{{ $learner->after_work_pathway }}</td><td>{{ $learner->created_at }}</td><td>{{ $learner->updated_at }}</td><td><div class="actions">
<button type="button" class="secondary small" data-dialog-open="learner-outcomes-{{ $learner->id }}">Update outcomes</button>
@unless($learner->learning_access_paid)<form method="post" action="/admin/mel/learners/{{ $learner->id }}/confirm-payment">@csrf<select name="cohort_id" aria-label="Cohort for {{ $learner->name }}" required><option value="">Select cohort</option>@foreach($cohorts->where('active',true) as $cohort)<option value="{{ $cohort->id }}">{{ $cohort->name }}</option>@endforeach</select><button class="small">Confirm payment</button></form>@else<span class="tag">Paid / active</span>@endunless
</div>
<dialog class="form-dialog" id="learner-outcomes-{{ $learner->id }}" aria-labelledby="learner-outcomes-title-{{ $learner->id }}"><div class="dialog-heading"><h2 id="learner-outcomes-title-{{ $learner->id }}">Update {{ $learner->name }} outcomes</h2><button class="secondary small" type="button" data-dialog-close>Close</button></div><form class="dialog-form" method="post" action="/admin/mel/learners/{{ $learner->id }}">@csrf @method('PUT')
<div class="field"><label>Verified learner outcomes</label><textarea name="verified_outcomes">{{ $learner->verified_outcomes }}</textarea></div><div class="field"><label>Other verified learner outcome</label><textarea name="other_verified_outcome">{{ $learner->other_verified_outcome }}</textarea></div>
<div class="field"><label>After-work status</label><select name="after_work_status"><option value="">Select</option>@foreach(['Working','Self-employed','Studying','Seeking work','Other'] as $status)<option @selected($learner->after_work_status===$status)>{{ $status }}</option>@endforeach</select></div><div class="field"><label>After-work pathway</label><input name="after_work_pathway" value="{{ $learner->after_work_pathway }}"></div><div class="dialog-actions"><button>Save outcome updates</button></div></form></dialog></td></tr>
@empty<tr><td colspan="27">No learner accounts yet.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><h2>Enrollment cohorts and learner-number format</h2><p>Set a cohort and category before confirming payment. Number formats support <code>{prefix}</code>, <code>{cohort}</code>, <code>{year}</code>, and <code>{sequence}</code>.</p>
<form method="post" action="/admin/mel/cohorts" class="grid">@csrf<div class="field"><label>Cohort name</label><input name="name" required></div><div class="field"><label>Enrollment category</label><input name="enrollment_category" required></div><div class="field"><label>Learner number prefix</label><input name="learner_number_prefix" required></div><div class="field"><label>Number format</label><input name="learner_number_format" value="{prefix}-{year}-{sequence}" required></div><div class="field"><label>Next sequence</label><input type="number" name="next_sequence" value="1" min="1" required></div><div class="field"><label>Sequence digits</label><input type="number" name="sequence_padding" value="4" min="1" max="10" required></div><div class="field"><label><input type="checkbox" name="active" value="1" checked> Active for enrollment</label></div><button>Add cohort</button></form>
<div class="table-wrap"><table><thead><tr><th>Cohort</th><th>Category</th><th>Prefix</th><th>Format</th><th>Next number</th><th>Status</th><th>Actions</th></tr></thead><tbody>
@forelse($cohorts as $cohort)<tr><td>{{ $cohort->name }}</td><td>{{ $cohort->enrollment_category }}</td><td>{{ $cohort->learner_number_prefix }}</td><td>{{ $cohort->learner_number_format }}</td><td>{{ $cohort->next_sequence }}</td><td>{{ $cohort->active?'Active':'Inactive' }}</td><td><div class="actions">
<button class="secondary small" type="button" data-dialog-open="edit-cohort-{{ $cohort->id }}">Edit</button><form method="post" action="/admin/mel/cohorts/{{ $cohort->id }}">@csrf @method('DELETE')<button class="danger small">Delete</button></form>
<dialog class="form-dialog" id="edit-cohort-{{ $cohort->id }}"><div class="dialog-heading"><h2>Edit {{ $cohort->name }}</h2><button class="secondary small" type="button" data-dialog-close>Close</button></div><form class="dialog-form" method="post" action="/admin/mel/cohorts/{{ $cohort->id }}">@csrf @method('PUT')@foreach(['name'=>'Cohort name','enrollment_category'=>'Enrollment category','learner_number_prefix'=>'Learner number prefix','learner_number_format'=>'Number format','next_sequence'=>'Next sequence','sequence_padding'=>'Sequence digits'] as $field=>$label)<div class="field"><label>{{ $label }}</label><input name="{{ $field }}" value="{{ $cohort->$field }}" @if(in_array($field,['next_sequence','sequence_padding']))type="number" min="1"@endif required></div>@endforeach<div class="field"><label><input type="checkbox" name="active" value="1" @checked($cohort->active)> Active</label></div><div class="dialog-actions"><button>Save cohort</button></div></form></dialog>
</div></td></tr>@empty<tr><td colspan="7">No cohorts configured.</td></tr>@endforelse
</tbody></table></div></section>
<section class="panel"><h2>Refugee settlements</h2><p>Active settlements appear for learners who identify as refugees.</p><form method="post" action="/admin/mel/settlements" class="toolbar">@csrf<div class="field"><label>Settlement name</label><input name="name" required></div><button>Add settlement</button></form><div class="actions">@forelse($settlements as $settlement)<span class="tag">{{ $settlement->name }} <form method="post" action="/admin/mel/settlements/{{ $settlement->id }}">@csrf @method('DELETE')<button class="danger small" aria-label="Remove {{ $settlement->name }}">Remove</button></form></span>@empty<p>No settlements configured.</p>@endforelse</div></section>
@foreach($categories as $key=>$meta)
<section class="panel"><h2>{{ $meta[0] }}</h2><form method="post" action="/admin/mel/{{ $key }}" class="grid">@csrf
@foreach(array_slice($meta,1) as [$field,$label,$type])<div class="field"><label>{{ $label }}</label><input name="{{ $field }}" type="{{ $type }}" @if($type==='number')step="any" min="0"@endif></div>@endforeach
<div class="field"><button type="submit">Add {{ $meta[0] }} record</button></div></form>
<div class="table-wrap"><table><thead><tr>@foreach(array_slice($meta,1) as [$field,$label])<th>{{ $label }}</th>@endforeach<th>Created at</th><th>Actions</th></tr></thead><tbody>
@forelse($records->where('category',$key) as $record)@php $values=(array)json_decode($record->data,true); @endphp<tr>@foreach(array_slice($meta,1) as [$field])<td>{{ $values[$field]??'' }}</td>@endforeach<td>{{ $record->created_at }}</td><td><form method="post" action="/admin/mel/{{ $key }}/{{ $record->id }}" data-confirm="Delete this record?">@csrf @method('DELETE')<button class="danger small">Delete</button></form></td></tr>@empty<tr><td colspan="{{ count($meta)+1 }}">No records yet.</td></tr>@endforelse</tbody></table></div></section>
@endforeach
<section class="panel"><h2>Payment gateways and methods</h2><p>Configure the payment destinations shown to learners. Add IOTEC, bank accounts, mobile money, or merchant codes.</p>
<form method="post" action="/admin/mel/payment-gateways" class="grid">@csrf
<div class="field"><label>Display name</label><input name="name" placeholder="e.g. Programme tuition" required></div>
<div class="field"><label>Payment type</label><select name="provider_type" required>@foreach(['IOTEC','Bank','Mobile Money','Merchant Code','Other'] as $type)<option>{{ $type }}</option>@endforeach</select></div>
<div class="field"><label>Provider / bank</label><input name="provider" placeholder="IOTEC, bank name, telecom"></div>
<div class="field"><label>Account holder</label><input name="account_name"></div>
<div class="field"><label>Account / phone number</label><input name="account_number"></div>
<div class="field"><label>Merchant code</label><input name="merchant_code"></div>
<div class="field"><label>Currency</label><select name="currency" required>@foreach(['UGX','USD','EUR','GBP','KES'] as $currency)<option>{{ $currency }}</option>@endforeach</select></div>
<div class="field"><label>Amount (optional)</label><input type="number" min="0" step="0.01" name="amount"></div>
<div class="field"><label>Payment instructions</label><textarea name="instructions" placeholder="Reference to use, steps, or other learner instructions"></textarea></div>
<div class="field"><label><input type="checkbox" name="active" value="1" checked> Show to learners</label></div><div class="field"><button type="submit">Add payment option</button></div></form>
<div class="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Provider</th><th>Account holder</th><th>Account / phone</th><th>Merchant code</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($gateways as $gateway)<tr><td>{{ $gateway->name }}</td><td>{{ $gateway->provider_type }}</td><td>{{ $gateway->provider }}</td><td>{{ $gateway->account_name }}</td><td>{{ $gateway->account_number }}</td><td>{{ $gateway->merchant_code }}</td><td>{{ $gateway->amount?number_format($gateway->amount,2).' '.$gateway->currency:'—' }}</td><td>{{ $gateway->active?'Active':'Hidden' }}</td><td><form method="post" action="/admin/mel/payment-gateways/{{ $gateway->id }}" data-confirm="Delete this payment option?">@csrf @method('DELETE')<button class="danger small">Delete</button></form></td></tr>@empty<tr><td colspan="9">No payment methods configured.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><h2>Supporting documents</h2><form method="post" action="/admin/mel/documents" enctype="multipart/form-data" class="grid">@csrf<div class="field"><label>Category</label><input name="category" required></div><div class="field"><label>Document</label><input name="document" required></div><div class="field"><label>Description</label><input name="description"></div><div class="field"><label>File</label><input name="file" type="file" required></div><button>Upload document</button></form>
<div class="table-wrap"><table><thead><tr><th>Category</th><th>Document</th><th>Description</th><th>File</th><th>Size</th><th>Uploaded by</th><th>Uploaded at</th><th>Actions</th></tr></thead><tbody>@forelse($documents as $doc)<tr><td>{{ $doc->category }}</td><td>{{ $doc->document }}</td><td>{{ $doc->description }}</td><td>{{ basename($doc->file_path) }}</td><td>{{ number_format($doc->size/1024,1) }} KB</td><td>{{ \App\Models\User::find($doc->uploaded_by)?->name }}</td><td>{{ $doc->created_at }}</td><td><div class="actions"><a class="button small" href="/admin/mel/documents/{{ $doc->id }}/download">Download</a><form method="post" action="/admin/mel/documents/{{ $doc->id }}">@csrf @method('DELETE')<button class="danger small">Delete</button></form></div></td></tr>@empty<tr><td colspan="8">No supporting documents uploaded.</td></tr>@endforelse</tbody></table></div></section>
@endsection
