@extends('layout')
@section('inline-form-feedback','1')
@section('content')
<div class="page-wrap"><a href="/admin/mel/surveys">Back to surveys</a><span class="eyebrow">Survey builder</span><h1 class="page-title">{{ $survey->title }}</h1>
<div class="toolbar"><button type="button" class="secondary" data-dialog-open="share-survey">Link / QR</button><a class="button secondary" href="/admin/mel/surveys/{{ $survey->id }}/responses">Responses and summary</a><form method="post" action="/admin/mel/surveys/{{ $survey->id }}/duplicate">@csrf<button type="submit" class="secondary">Duplicate survey</button></form></div>
@if($locked)<div class="notice">Responses have been received. Questions and response identity mode are locked to preserve those answers. Duplicate this survey to build a revised version.</div>@else<p class="page-intro">Add questions, choose their answer types, and reorder them. Publish when your form is ready to receive responses.</p>@endif
<form method="post" action="/admin/mel/surveys/{{ $survey->id }}" data-survey-builder data-locked="{{ $locked?'1':'0' }}">@csrf @method('PUT')
<x-form-feedback />
<section class="panel"><div class="field"><label for="survey-title">Survey title</label><input id="survey-title" name="title" value="{{ old('title',$survey->title) }}" maxlength="255" required></div><div class="field"><label for="survey-description">Introduction</label><textarea id="survey-description" name="description" maxlength="10000">{{ old('description',$survey->description) }}</textarea></div>
@php $anonymousMode=(bool)($locked?$survey->anonymous:old('anonymous',$survey->anonymous)); @endphp
<div class="content-choice-grid"><div class="field"><label for="survey-mode">Response identity</label><select id="survey-mode" name="anonymous" @disabled($locked)><option value="1" @selected($anonymousMode)>Anonymous</option><option value="0" @selected(!$anonymousMode)>Named (name and email)</option></select></div><div class="field"><label for="survey-status">Status</label><select id="survey-status" name="status">@foreach(['draft','published','closed'] as $status)<option value="{{ $status }}" @selected(old('status',$survey->status)===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="field"><label for="survey-opens">Opens (optional)</label><input id="survey-opens" name="opens_at" type="datetime-local" value="{{ old('opens_at',$survey->opens_at?\Carbon\Carbon::parse($survey->opens_at)->format('Y-m-d\TH:i'):'') }}"></div><div class="field"><label for="survey-closes">Closes (optional)</label><input id="survey-closes" name="closes_at" type="datetime-local" value="{{ old('closes_at',$survey->closes_at?\Carbon\Carbon::parse($survey->closes_at)->format('Y-m-d\TH:i'):'') }}"></div></div>
<p class="muted">Anonymous responses are stored without the respondent's account, name or email. Avoid asking identifying questions if the survey is meant to be anonymous.</p></section>
<fieldset class="survey-question-list" @disabled($locked)><legend>Survey questions</legend><div data-survey-questions>@foreach($locked?$questions:old('questions',$questions) as $index=>$question)@include('admin.survey-question')@endforeach</div>@unless($locked)<button type="button" class="secondary" data-question-add><i class="fas fa-plus" aria-hidden="true"></i> Add question</button>@endunless</fieldset><div class="survey-save-bar"><button type="submit">Save survey</button><small>Published surveys accept responses during their opening window.</small></div>
</form>
@unless($locked)<template data-survey-question-template>@include('admin.survey-question',['index'=>'__INDEX__','question'=>['id'=>'__ID__','type'=>'short_text','label'=>'','required'=>false,'help'=>'','options'=>[]]])</template>@endunless
<x-share-dialog id="share-survey" :title="$survey->title" :url="url('/surveys/'.$survey->token)" :qrUrl="'/admin/mel/surveys/'.$survey->id.'/qr.svg'" />
</div>
@endsection
