<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{AuthController,PublicController,CmsController,PortalController,ReviewController};
Route::get('/',[PublicController::class,'home']);
Route::get('/pages/{slug}',[PublicController::class,'page']);
Route::get('/search',[PublicController::class,'search']);
Route::post('/help/chat',[PublicController::class,'chat'])->middleware('throttle:30,1');
Route::get('/faq', [PublicController::class,'help'])->defaults('page','faq');
Route::get('/user-guide', [PublicController::class,'help'])->defaults('page','guide');
Route::get('/contact',[PublicController::class,'contact']);
Route::post('/contact',[PublicController::class,'sendContact'])->middleware('throttle:5,1');
Route::get('/explore/{type}',[PublicController::class,'listing']);
Route::get('/explore/{type}/{id}',[PublicController::class,'detail']);
Route::middleware('guest')->group(function(){
 Route::get('/login',[AuthController::class,'form'])->name('login');Route::post('/login',[AuthController::class,'login'])->middleware('throttle:login');
 Route::get('/register',[AuthController::class,'registerForm']);Route::post('/register',[AuthController::class,'register'])->middleware('throttle:5,1');
 Route::get('/forgot-password',[AuthController::class,'forgot'])->name('password.request');Route::post('/forgot-password',[AuthController::class,'sendReset'])->middleware('throttle:5,1');
 Route::get('/reset-password/{token}',[AuthController::class,'resetForm'])->name('password.reset');Route::post('/reset-password',[AuthController::class,'reset']);
});
Route::middleware(['auth','active'])->group(function(){
  Route::post('/logout',[AuthController::class,'logout']);Route::get('/dashboard',[PortalController::class,'dashboard']);
   Route::get('/admin/site-settings',[CmsController::class,'siteSettings']);Route::put('/admin/site-settings',[CmsController::class,'saveSiteSettings']);
   Route::put('/admin/site-settings/ai',[CmsController::class,'saveAiSettings']);
   Route::post('/admin/site-settings/ai/test',[CmsController::class,'testAiConnection'])->middleware('throttle:5,1');
  Route::post('/admin/site-settings/payment-gateways', [\App\Http\Controllers\MelController::class,'saveGateway']);
  Route::delete('/admin/site-settings/payment-gateways/{id}', [\App\Http\Controllers\MelController::class,'deleteGateway']);
   Route::get('/admin/enrollment', [\App\Http\Controllers\MelController::class,'enrollment']);
   Route::get('/admin/enrollment/template.csv', [\App\Http\Controllers\MelController::class,'enrollmentTemplate']);
   Route::post('/admin/enrollment/import', [\App\Http\Controllers\MelController::class,'importEnrollment'])->middleware('throttle:5,1');
   Route::post('/admin/enrollment/bulk', [\App\Http\Controllers\MelController::class,'bulkEnrollment']);
  Route::post('/admin/enrollment/cohorts', [\App\Http\Controllers\MelController::class,'saveCohort']);
  Route::put('/admin/enrollment/cohorts/{id}', [\App\Http\Controllers\MelController::class,'saveCohort']);
  Route::delete('/admin/enrollment/cohorts/{id}', [\App\Http\Controllers\MelController::class,'deleteCohort']);
  Route::post('/admin/enrollment/settlements', [\App\Http\Controllers\MelController::class,'addSettlement']);
  Route::delete('/admin/enrollment/settlements/{id}', [\App\Http\Controllers\MelController::class,'deleteSettlement']);
  Route::post('/admin/enrollment/learners/{id}/confirm-payment', [\App\Http\Controllers\MelController::class,'confirmPayment']);
  Route::put('/admin/enrollment/learners/{id}/outcomes', [\App\Http\Controllers\MelController::class,'updateLearner']);
  Route::get('/profile',[PortalController::class,'section'])->defaults('section','profile');
  Route::get('/learning/content/resources/{id}',[PortalController::class,'resource']);
 Route::get('/portal/{section}',[PortalController::class,'section']);Route::get('/learning/{id}',[PortalController::class,'course']);
 Route::post('/actions/{action}',[PortalController::class,'action']);Route::post('/profile',[PortalController::class,'profile']);
 Route::post('/notifications/{id}/read',[PortalController::class,'readNotice']);Route::get('/files/{type}/{id}',[PortalController::class,'download']);Route::get('/certificates/{id}',[PortalController::class,'certificate']);
  Route::get('/admin/reports/impact.csv',[ReviewController::class,'report']);
   Route::get('/admin/mel',[\App\Http\Controllers\MelController::class,'index']);
    Route::post('/admin/mel/documents', [\App\Http\Controllers\MelController::class,'upload']);
    Route::post('/admin/mel/{category}',[\App\Http\Controllers\MelController::class,'save']);
  Route::delete('/admin/mel/{category}/{id}',[\App\Http\Controllers\MelController::class,'delete']);
  Route::get('/admin/mel/documents/{id}/download',[\App\Http\Controllers\MelController::class,'downloadDocument']);
  Route::delete('/admin/mel/documents/{id}',[\App\Http\Controllers\MelController::class,'deleteDocument']);
 Route::get('/admin/reviews/{type}',[ReviewController::class,'index']);Route::post('/admin/reviews/{type}/{id}',[ReviewController::class,'update']);
 Route::get('/admin/{module}',[CmsController::class,'index']);Route::get('/admin/{module}/create',[CmsController::class,'form']);Route::get('/admin/{module}/{id}/edit',[CmsController::class,'form']);
 Route::post('/admin/{module}',[CmsController::class,'save']);Route::put('/admin/{module}/{id}',[CmsController::class,'save']);Route::delete('/admin/{module}/{id}',[CmsController::class,'delete']);
});
