<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{AuthController,PublicController,CmsController,PortalController,ReviewController};
Route::get('/',[PublicController::class,'home']);
Route::get('/calls',[\App\Http\Controllers\CallController::class,'listing']);
Route::get('/calls/{token}',[\App\Http\Controllers\CallController::class,'show']);
Route::get('/events/{token}',[\App\Http\Controllers\EventController::class,'show']);
Route::post('/events/{token}/register',[\App\Http\Controllers\EventController::class,'register'])->middleware('throttle:10,1');
Route::get('/surveys/{token}',[\App\Http\Controllers\SurveyController::class,'show']);
Route::post('/surveys/{token}',[\App\Http\Controllers\SurveyController::class,'submit'])->middleware('throttle:20,1');
Route::get('/pages/{slug}',[PublicController::class,'page']);
Route::get('/search',[PublicController::class,'search']);
Route::post('/help/chat',[PublicController::class,'chat'])->middleware('throttle:30,1');
Route::get('/faq', [PublicController::class,'help'])->defaults('page','faq');
Route::get('/user-guide', [PublicController::class,'help'])->defaults('page','guide');
Route::get('/contact',[PublicController::class,'contact']);
Route::post('/contact',[PublicController::class,'sendContact'])->middleware('throttle:5,1');
Route::get('/explore/{type}',[PublicController::class,'listing']);
Route::get('/explore/{type}/{id}',[PublicController::class,'detail']);
Route::middleware('guest')->group(function(){
 Route::get('/login',[AuthController::class,'form'])->name('login');Route::post('/login',[AuthController::class,'login'])->middleware('throttle:login');
 Route::get('/register',[AuthController::class,'registerForm']);Route::post('/register',[AuthController::class,'register'])->middleware('throttle:5,1');
 Route::get('/forgot-password',[AuthController::class,'forgot'])->name('password.request');Route::post('/forgot-password',[AuthController::class,'sendReset'])->middleware('throttle:5,1');
 Route::get('/reset-password/{token}',[AuthController::class,'resetForm'])->name('password.reset');Route::post('/reset-password',[AuthController::class,'reset']);
});
Route::middleware(['auth','active'])->group(function(){
  Route::middleware(\App\Http\Middleware\EnsureLearningAccess::class)->group(function(){
    Route::get('/calls/{token}/apply',[\App\Http\Controllers\CallController::class,'show']);
    Route::post('/calls/{token}/apply',[\App\Http\Controllers\CallController::class,'apply'])->middleware('throttle:5,1');
  });

 Route::get('/admin/calls',[\App\Http\Controllers\CallController::class,'index']);
 Route::get('/admin/certificates',[\App\Http\Controllers\CertificateController::class,'index']);
 Route::post('/admin/certificates',[\App\Http\Controllers\CertificateController::class,'create']);
 Route::get('/admin/certificates/events/{id}/template',[\App\Http\Controllers\CertificateController::class,'eventEditor']);
 Route::put('/admin/certificates/events/{id}/template',[\App\Http\Controllers\CertificateController::class,'saveEvent']);
 Route::get('/admin/certificates/events/{id}/background',[\App\Http\Controllers\CertificateController::class,'eventBackground']);
 Route::get('/admin/certificates/events/{id}/preview.pdf',[\App\Http\Controllers\CertificateController::class,'eventPreview']);
 Route::get('/admin/certificates/{id}/template',[\App\Http\Controllers\CertificateController::class,'editor']);
 Route::put('/admin/certificates/{id}/template',[\App\Http\Controllers\CertificateController::class,'save']);
 Route::get('/admin/certificates/{id}/background',[\App\Http\Controllers\CertificateController::class,'background']);
 Route::get('/admin/certificates/{id}/preview.pdf',[\App\Http\Controllers\CertificateController::class,'preview']);
 Route::post('/admin/certificates/{id}/recommend',[\App\Http\Controllers\CertificateController::class,'recommend']);
 Route::get('/certificates/{id}/file',[\App\Http\Controllers\CertificateController::class,'download']);
 Route::post('/admin/calls',[\App\Http\Controllers\CallController::class,'save']);
 Route::put('/admin/calls/{id}',[\App\Http\Controllers\CallController::class,'save']);
 Route::get('/admin/calls/{id}/qr.svg',[\App\Http\Controllers\CallController::class,'qr']);
 Route::put('/admin/calls/applications/{id}',[\App\Http\Controllers\CallController::class,'review']);
  Route::post('/logout',[AuthController::class,'logout']);Route::get('/dashboard',[PortalController::class,'dashboard']);
   Route::get('/admin/site-settings',[CmsController::class,'siteSettings']);Route::put('/admin/site-settings',[CmsController::class,'saveSiteSettings']);
   Route::put('/admin/site-settings/ai',[CmsController::class,'saveAiSettings']);
   Route::post('/admin/site-settings/ai/test',[CmsController::class,'testAiConnection'])->middleware('throttle:5,1');
  Route::post('/admin/site-settings/payment-gateways', [\App\Http\Controllers\MelController::class,'saveGateway']);
  Route::delete('/admin/site-settings/payment-gateways/{id}', [\App\Http\Controllers\MelController::class,'deleteGateway']);
   Route::get('/admin/enrollment', [\App\Http\Controllers\MelController::class,'enrollment']);
   Route::get('/admin/enrollment/template.csv', [\App\Http\Controllers\MelController::class,'enrollmentTemplate']);
   Route::post('/admin/enrollment/import', [\App\Http\Controllers\MelController::class,'importEnrollment'])->middleware('throttle:5,1');
   Route::post('/admin/enrollment/bulk', [\App\Http\Controllers\MelController::class,'bulkEnrollment']);
  Route::post('/admin/enrollment/cohorts', [\App\Http\Controllers\MelController::class,'saveCohort']);
  Route::put('/admin/enrollment/cohorts/{id}', [\App\Http\Controllers\MelController::class,'saveCohort']);
  Route::delete('/admin/enrollment/cohorts/{id}', [\App\Http\Controllers\MelController::class,'deleteCohort']);
  Route::post('/admin/enrollment/settlements', [\App\Http\Controllers\MelController::class,'addSettlement']);
  Route::delete('/admin/enrollment/settlements/{id}', [\App\Http\Controllers\MelController::class,'deleteSettlement']);
  Route::post('/admin/enrollment/learners/{id}/confirm-payment', [\App\Http\Controllers\MelController::class,'confirmPayment']);
  Route::put('/admin/enrollment/learners/{id}/outcomes', [\App\Http\Controllers\MelController::class,'updateLearner']);
  Route::get('/profile',[PortalController::class,'section'])->defaults('section','profile');
   Route::get('/portal/payment',[PortalController::class,'section'])->defaults('section','payment');
  Route::middleware(\App\Http\Middleware\EnsureLearningAccess::class)->group(function(){
    Route::get('/learning/content/resources/{id}',[PortalController::class,'resource']);
    Route::get('/learning/content/lessons/{id}',[PortalController::class,'lessonMedia']);
    Route::get('/portal/{section}',[PortalController::class,'section']);
    Route::get('/learning/{id}',[PortalController::class,'course']);
    Route::post('/actions/{action}',[PortalController::class,'action']);
    Route::post('/notifications/{id}/read',[PortalController::class,'readNotice']);
    Route::get('/files/{type}/{id}',[PortalController::class,'download']);
    Route::get('/certificates/{id}',[PortalController::class,'certificate']);
  });
  Route::post('/profile',[PortalController::class,'profile']);

  Route::get('/admin/reports/impact.csv',[ReviewController::class,'report']);
  Route::get('/admin/events',[\App\Http\Controllers\EventController::class,'index']);
  Route::get('/admin/events/{id}/qr.svg',[\App\Http\Controllers\EventController::class,'qr'])->whereNumber('id');
  Route::get('/admin/events/{id}/attendance',[\App\Http\Controllers\EventController::class,'attendance'])->whereNumber('id');
  Route::post('/admin/events/{id}/attendance/{registration}',[\App\Http\Controllers\EventController::class,'mark'])->whereNumber(['id','registration']);
  Route::get('/admin/events/{id}/attendance.csv',[\App\Http\Controllers\EventController::class,'export'])->whereNumber('id');
  Route::get('/admin/mel/surveys',[\App\Http\Controllers\SurveyController::class,'index']);
  Route::post('/admin/mel/surveys',[\App\Http\Controllers\SurveyController::class,'create']);
  Route::get('/admin/mel/surveys/{id}/edit',[\App\Http\Controllers\SurveyController::class,'edit'])->whereNumber('id');
  Route::put('/admin/mel/surveys/{id}',[\App\Http\Controllers\SurveyController::class,'update'])->whereNumber('id');
  Route::post('/admin/mel/surveys/{id}/duplicate',[\App\Http\Controllers\SurveyController::class,'duplicate'])->whereNumber('id');
  Route::get('/admin/mel/surveys/{id}/qr.svg',[\App\Http\Controllers\SurveyController::class,'qr'])->whereNumber('id');
  Route::get('/admin/mel/surveys/{id}/responses',[\App\Http\Controllers\SurveyController::class,'responses'])->whereNumber('id');
  Route::get('/admin/mel/surveys/{id}/responses.csv',[\App\Http\Controllers\SurveyController::class,'export'])->whereNumber('id');
   Route::get('/admin/mel',[\App\Http\Controllers\MelController::class,'index']);
    Route::post('/admin/mel/documents', [\App\Http\Controllers\MelController::class,'upload']);
    Route::post('/admin/mel/{category}',[\App\Http\Controllers\MelController::class,'save']);
  Route::delete('/admin/mel/{category}/{id}',[\App\Http\Controllers\MelController::class,'delete']);
  Route::get('/admin/mel/documents/{id}/download',[\App\Http\Controllers\MelController::class,'downloadDocument']);
  Route::delete('/admin/mel/documents/{id}',[\App\Http\Controllers\MelController::class,'deleteDocument']);
 Route::get('/admin/reviews/{type}',[ReviewController::class,'index']);Route::post('/admin/reviews/{type}/{id}',[ReviewController::class,'update']);
 Route::get('/admin/{module}',[CmsController::class,'index']);Route::get('/admin/{module}/create',[CmsController::class,'form']);Route::get('/admin/{module}/{id}/edit',[CmsController::class,'form']);
 Route::post('/admin/{module}',[CmsController::class,'save']);Route::put('/admin/{module}/{id}',[CmsController::class,'save']);Route::delete('/admin/{module}/{id}',[CmsController::class,'delete']);
});
