<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\{DB,Storage};

class MelController extends Controller
{
 private const CATEGORIES=['teachers'=>['Teachers / educators',['date','Date','date'],['name','Name','text'],['gender','Gender','text'],['age','Age','number'],['refugee','Refugee','text'],['host_community','Host Community','text'],['urban_rural','Urban/Rural','text'],['pwd','PWD','text']], 'schools'=>['Schools',['date','Date','date'],['school','School / Institution','text'],['urban_rural','Urban/Rural','text'],['ownership','Ownership','text'],['level','Level','text']], 'other_users'=>['Other users',['date','Date','date'],['gender','Gender','text'],['host_community','Host Community','text'],['urban_rural','Urban/Rural','text'],['pwd','PWD','text'],['education','Education','text']], 'employment'=>['Employment',['date','Date','date'],['name','Name','text'],['gender','Gender','text'],['age','Age','number'],['pwd','PWD','text'],['type','Type','text'],['role','Role','text'],['status','Status','text']], 'finance'=>['Finance',['date','Date','date'],['amount','Amount USD','number'],['form','Form','text'],['source','Source','text']], 'partnerships'=>['Partnerships',['date','Date','date'],['partner','Partner','text'],['type','Type','text'],['status','Status','text']], 'revenue'=>['Revenue',['month','Month','text'],['gross_revenue','Gross Revenue (UGX)','number'],['stream','Stream','text']]];
 private function authorize(Request $r): void {abort_unless($r->user()->manager(),403);}
 public function index(Request $r){$this->authorize($r);$counts=[];$learners=DB::table('users')->where('role','participant');$total=(clone $learners)->count();$counts['Total Learners Reached']=$total;$counts['Female New Learners']=($total?round((clone $learners)->where('gender','Female')->count()*100/$total,1):0).'%';$counts['Refugees']=(clone $learners)->where('refugee',true)->count();$counts['PWDs']=(clone $learners)->where('pwd',true)->count();$counts['New Learners']=(clone $learners)->whereYear('created_at',now()->year)->count();$counts['Teachers/Educators Reached']=DB::table('mel_records')->where('category','teachers')->count();$counts['Schools reached']=DB::table('mel_records')->where('category','schools')->count();$counts['Other users']=DB::table('mel_records')->where('category','other_users')->count();$counts['Employees']=DB::table('mel_records')->where('category','employment')->count();$rows=DB::table('mel_records')->get();$amount=fn($category,$field)=>(float)$rows->where('category',$category)->sum(fn($r)=>(float)(json_decode($r->data,true)[$field]??0));$counts['Finance Raised (USD)']=number_format($amount('finance','amount'),2);$counts['Partnerships']=DB::table('mel_records')->where('category','partnerships')->count();$counts['Cumulative Revenue']=number_format($amount('revenue','gross_revenue'));$counts['Youth in Work']=(clone $learners)->where('after_work_status','Working')->count();return view('admin.mel',['categories'=>self::CATEGORIES,'records'=>$rows->sortByDesc('id'),'documents'=>DB::table('mel_documents')->latest()->get(),'gateways'=>DB::table('payment_gateways')->orderBy('name')->get(),'counts'=>$counts]);}
 public function save(Request $r,string $category){$this->authorize($r);abort_unless(isset(self::CATEGORIES[$category]),404);$rules=[];foreach(array_slice(self::CATEGORIES[$category],1) as [$key,$label,$type])$rules[$key]=['nullable',$type==='number'?'numeric':($type==='date'?'date':'string'),$type==='number'?'max:999999999999':'max:5000'];$data=$r->validate($rules);DB::table('mel_records')->insert(['category'=>$category,'data'=>json_encode($data),'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','MEL record saved.');}
 public function delete(Request $r,string $category,string $id){$this->authorize($r);DB::table('mel_records')->where('category',$category)->where('id',$id)->delete();return back()->with('success','MEL record deleted.');}
 public function upload(Request $r){$this->authorize($r);$d=$r->validate(['category'=>'required|string|max:100','document'=>'required|string|max:255','description'=>'nullable|string|max:5000','file'=>'required|file|max:20480']);$file=$d['file'];DB::table('mel_documents')->insert(['category'=>$d['category'],'document'=>$d['document'],'description'=>$d['description']??null,'file_path'=>$file->store('mel-documents','local'),'size'=>$file->getSize(),'uploaded_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Supporting document uploaded.');}
 public function deleteDocument(Request $r,string $id){$this->authorize($r);$doc=DB::table('mel_documents')->findOrFail($id);Storage::disk('local')->delete($doc->file_path);DB::table('mel_documents')->where('id',$id)->delete();return back()->with('success','Document deleted.');}
 public function confirmPayment(Request $r,string $id){$this->authorize($r);DB::table('users')->where('id',$id)->where('role','participant')->update(['learning_access_paid'=>true,'updated_at'=>now()]);return back()->with('success','Learner learning access activated.');}
 public function saveGateway(Request $r){$this->authorize($r);$d=$r->validate(['name'=>'required|string|max:120','provider_type'=>'required|in:IOTEC,Bank,Mobile Money,Merchant Code,Other','provider'=>'nullable|string|max:120','account_name'=>'nullable|string|max:190','account_number'=>'nullable|string|max:100','merchant_code'=>'nullable|string|max:100','currency'=>'required|string|in:UGX,USD,EUR,GBP,KES','amount'=>'nullable|numeric|min:0|max:999999999999.99','instructions'=>'nullable|string|max:5000','active'=>'nullable|boolean']);$d['active']=$r->boolean('active');DB::table('payment_gateways')->insert($d+['created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Payment option saved.');}
 public function deleteGateway(Request $r,string $id){$this->authorize($r);DB::table('payment_gateways')->where('id',$id)->delete();return back()->with('success','Payment option deleted.');}
}
