@extends('layout') @section('content')<span class="eyebrow">Your learning journey</span><h1>{{ match($section){'learn'=>'My learning','practice'=>'Practical skills','mentorship'=>'Mentorship','enterprise'=>'Enterprise & earnings',default=>ucfirst($section)} }}</h1>
@if($section==='learn')<div class="grid">@forelse($data['courses'] as $c)@php $enrolled=collect($data['enrolments'])->contains('course_id',$c->id); @endphp<article class="card"><span class="tag">{{ $c->level }} · {{ $c->duration_hours }} hours</span><h3>{{ $c->title }}</h3><p>{{ $c->summary }}</p>@if($enrolled)@include('portal.progress',['progressCourseId'=>$c->id])<a class="button" href="/learning/{{ $c->id }}">Continue learning</a>@else<form method="post" action="/actions/enrol">@csrf<input type="hidden" name="course_id" value="{{ $c->id }}"><button>Enrol now</button></form>@endif</article>@empty<div class="empty">No courses are currently published.</div>@endforelse</div>
@elseif($section==='practice')<p>Record what you practised and what you learned. Programme staff can verify your practical experience.</p><form class="panel" method="post" action="/actions/practice">@csrf<div class="field"><label>Skill</label><select name="skill_id" required>@foreach($data['skills'] as $s)<option value="{{ $s->id }}">{{ $s->title }}</option>@endforeach</select></div>@foreach(['title'=>'What did you practise?','minutes'=>'Minutes spent','practised_on'=>'Date'] as $f=>$label)<div class="field"><label>{{ $label }}</label><input type="{{ $f==='minutes'?'number':($f==='practised_on'?'date':'text') }}" name="{{ $f }}" required></div>@endforeach<div class="field"><label>Describe your activity and learning</label><textarea name="body" required></textarea></div><button>Save practical log</button></form>@foreach($data['practice_logs'] as $log)<article class="panel"><span class="tag">{{ $log->status }}</span><h3>{{ $log->title }}</h3><p>{{ $log->body }}</p><small>{{ $log->practised_on }} · {{ $log->minutes }} minutes</small>@if($log->feedback)<p>Feedback: {{ $log->feedback }}</p>@endif</article>@endforeach
@elseif($section==='mentorship')<h2>Find a mentor</h2><div class="grid">@foreach($data['mentors'] as $m)<article class="card"><h3>{{ $m->name }}</h3><span class="tag">{{ $m->expertise }}</span><p>{{ $m->bio }}</p></article>@endforeach</div><h2>Available sessions</h2>@forelse($data['slots'] as $s)<details><summary>{{ $s->title }} · {{ $s->starts_at }} · {{ $s->mode }}</summary><p>{{ $s->location }} · {{ collect($data['mentors'])->firstWhere('id',$s->mentor_id)?->name }}</p><form method="post" action="/actions/book">@csrf<input type="hidden" name="slot_id" value="{{ $s->id }}"><div class="field"><label>What would you like help with?</label><textarea name="goal" required></textarea></div><button>Request session</button></form></details>@empty<p class="muted">No available sessions. Check back soon.</p>@endforelse<h2>My requests</h2>@foreach($data['bookings'] as $b)<article class="panel"><span class="tag">{{ $b->status }}</span><h3>{{ $b->session_title }}</h3><small>{{ $b->starts_at }} · {{ $b->mentor_name }} · {{ $b->mode }}</small><p>{{ $b->location }}</p><p>{{ $b->goal }}</p><p>{{ $b->notes }}</p>@if(in_array($b->status,['requested','confirmed']))<form method="post" action="/actions/cancel-booking" data-confirm="Cancel your mentorship request?">@csrf<input type="hidden" name="booking_id" value="{{ $b->id }}"><button class="secondary">Cancel request</button></form>@endif</article>@endforeach
@elseif($section==='opportunities')@forelse($data['opportunities'] as $o)<details><summary>{{ $o->title }} · {{ $o->type }}</summary><p>{{ $o->organisation }} · {{ $o->location }} · Apply by {{ $o->deadline }}</p><p class="prose">{{ $o->description }}</p>@php $app=collect($data['applications'])->firstWhere('opportunity_id',$o->id); @endphp @if($app)<p><strong>Application: {{ $app->status }}</strong> {{ $app->feedback }}</p>@else<form method="post" action="/actions/apply">@csrf<input type="hidden" name="opportunity_id" value="{{ $o->id }}"><div class="field"><label>Tell us why you are interested and what skills you bring</label><textarea name="motivation" required></textarea></div><button>Submit application</button></form>@endif</details>@empty<div class="empty">No open opportunities.</div>@endforelse<h2>My application history</h2>@foreach($data['applications'] as $a)<p>Opportunity #{{ $a->opportunity_id }} · {{ $a->status }} · {{ $a->feedback }}</p>@endforeach
@elseif($section==='enterprise')
@include('portal.enterprise')
@elseif($section==='events')@include('portal.events')
@elseif($section==='notifications')@forelse($data['notifications'] as $n)<article class="panel"><small>{{ $n->created_at }} · {{ $n->read_at?'Read':'Unread' }}</small><h3>{{ $n->data['title']??'Notification' }}</h3><p>{{ $n->data['body']??'' }}</p>@if(!$n->read_at)<form method="post" action="/notifications/{{ $n->id }}/read">@csrf<button class="secondary">Mark as read</button></form>@endif</article>@empty<div class="empty">No notifications yet.</div>@endforelse
@elseif($section==='profile')<form class="panel" method="post" action="/profile">@csrf @foreach(['name','phone','district'] as $f)<div class="field"><label>{{ ucfirst($f) }}</label><input name="{{ $f }}" value="{{ old($f,$data['user'][$f]) }}" @required($f==='name')></div>@endforeach<p>Email: {{ $data['user']['email'] }}</p><button>Save profile</button></form>@endif @endsection
